version: '3.8'

services:
  respirex-backend:
    build: .
    ports:
      - "10000:10000"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount models directory for local development
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
