services:
  - type: web
    name: respiratory-disease-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
