services:
  - type: web
    name: respiratory-disease-api
    env: python
    plan: free
    pythonVersion: "3.10"
    buildCommand: pip install --only-binary=all --upgrade pip && pip install --only-binary=all -r requirements.txt
    startCommand: uvicorn main_lightweight:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
