services:
  - type: web
    name: respiratory-disease-api
    env: python
    plan: free
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: python -m uvicorn test_app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
