services:
  - type: web
    name: respirex-api-v11
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000